features:
  - jLeftElbow_x
  - jLeftElbow_y 
  - jLeftElbow_z
  - jRightElbow_x 
  - jRightElbow_y
  - jRightElbow_z
  - jLeftWrist_x
  - jLeftWrist_y
  - jLeftWrist_z
  - jRightWrist_x
  - jRightWrist_y
  - jRightWrist_z
  - jLeftShoulder_x
  - jLeftShoulder_y
  - jLeftShoulder_z
  - jRightShoulder_x
  - jRightShoulder_y
  - jRightShoulder_z
  - jLeftHip_x
  - jLeftHip_y
  - jLeftHip_z
  - jRightHip_x
  - jRightHip_y
  - jRightHip_z

types:
 - Strokes
 - Healthies


tasks: ['T01', 'T02', 'T03', 'T04', 'T05' , 'T06', 'T07', 'T08', 'T09', 'T10', 'T11', 'T12', 'T13', 'T14', 'T15', 'T16',
'T17','T18','T19','T20','T21','T22','T23','T24','T25','T26','T27','T28','T29','T30']

cutoff_length: 1024
resample: numpy