infra: classification
model: basicLSTM

BasicLSTM:
  sequence_len: 256
  feature_size: 24
  num_classes: 30
  hidden_size: 32
  num_layers: 4
  fcn_filter: 4
  dropout: 0.3



optimizer:
  lr: 0.0001
  betas: [0.9,0.99]
  weight_decay: 0.00001


num_classes: 30
batch_size: 32
