infra: classification
model: basicConv1d

BasicConv1d:
  sequence_len: 1024
  feature_size: 24
  num_classes: 30
  hidden_size: [64,32,16,8]



optimizer:
  lr: 0.0001
  betas: [0.9,0.99]
  weight_decay: 0.00001


num_classes: 30
batch_size: 32
