diffusion:
  seq_length: 1024
  feature_size: 24
  label_dim: 30
  timesteps: 20
  sampling_timesteps: 20
  loss_type: 'l2'
  beta_schedule: 'linear'
  use_ff: False



backbone:
  n_feat: 24
  n_channel: 1024
  n_layer_enc: 4
  n_layer_dec: 4
  d_model: 64
  n_heads: 16
  attn_pdrop: 0.1,
  resid_pdrop: 0.1,
  mlp_hidden_times: 4,
  block_activate: GELU
  max_len: 1024
  kernel_size: 5
  padding: 2 
  label_dim: 30

optimizer:
  lr: 0.00001
  betas: [0.9,0.99]

batch_size: 8