diffusion:
  seq_length: 1024
  feature_size: 24
  label_dim: 30
  timesteps: 512
  sampling_timesteps: 512
  loss_type: 'l1'
  beta_schedule: 'linear'
  use_ff: False



backbone:
  seq_len: 1024
  feature_dim: 24
  num_classes: 30
  hidden_ch: 64
  emb_dim: 32

optimizer:
  lr: 0.001
  betas: [0.9,0.99]