infra: classification
model: inception-time

inception-time:
  sequence_len: 1024
  feature_size: 24
  label_dim: 30
  inception_filter: 4
  fcn_filter: 4
  depth: 2
  fcn_layers: 2
  kernels: [10,20,40]
  dropout: 0.5
  use_residual: False
  use_bottleneck: True


optimizer:
  lr: 0.0001
  betas: [0.9,0.99]
  weight_decay: 0.00001


num_classes: 30
batch_size: 32
