generator:
  seq_len: 1024
  channels: 24
  num_classes: 30
  latent_dim: 64
  data_embed_dim: 64
  label_embed_dim: 16
  depth: 3
  num_heads: 4
  forward_drop_rate: 0.5
  attn_drop_rate: 0.5


discriminator:
  in_channels: 24
  patch_size: 16
  num_heads: 4
  data_emb_size: 64
  label_emb_size: 16
  seq_length: 1024
  depth: 3
  n_classes: 30


g_optim:
  lr: 0.001
  betas: [0.9,0.99]

d_optim:
  lr: 0.001
  betas: [0.9,0.99]


batch_size: 8
lamdba_cls: 1
lambda_gp: 10